[platformio]
lib_dir = /Users/amp/Dropbox/Arduino/libraries

[env:nano]
platform = atmelavr
framework = arduino
board = nanoatmega328
build_flags = -DDEBUG_LEVEL=5 -DSERIAL_TYPE=0


[env:1284]
platform = atmelavr
framework = arduino
board = 1284p16m
#board = moteinomega
build_flags = -DDEBUG_LEVEL=5 -DSERIAL_TYPE=1
upload_port = /dev/cu.usbserial-FTFO9I0N
